# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\desk_photos\downloder_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 575)
        Form.setAutoFillBackground(True)
        Form.setStyleSheet("\n"
"font: 10pt \"MV Boli\";")
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 181))
        self.label.setStyleSheet("background-image: url(:/newPrefix/5548fb2d8fe42184514afeb89c0e8f3d.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 130, 421, 451))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/5548fb2d8fe42184514afeb89c0e8f3d.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_3.setStyleSheet("font-weight:bold;")
        self.label_3.setObjectName("label_3")
        self.LINE_PATH = QtWidgets.QLineEdit(Form)
        self.LINE_PATH.setGeometry(QtCore.QRect(10, 140, 211, 20))
        self.LINE_PATH.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"\n"
"border-style:sold;\n"
"border-radius:8px;")
        self.LINE_PATH.setObjectName("LINE_PATH")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(20, 490, 151, 16))
        self.label_10.setObjectName("label_10")
        self.Btn_BROWSE = QtWidgets.QPushButton(Form)
        self.Btn_BROWSE.setGeometry(QtCore.QRect(230, 140, 71, 21))
        self.Btn_BROWSE.setMouseTracking(True)
        self.Btn_BROWSE.setTabletTracking(True)
        self.Btn_BROWSE.setAutoFillBackground(False)
        self.Btn_BROWSE.setStyleSheet("QPushButton{\n"
"   background-color: rgb(222, 193, 161);\n"
"    box-shadow: 0px 1px 0px 0px #1c1b18;\n"
"    background:linear-gradient(to bottom, #eae0c2 5%, #ccc2a6 100%);\n"
"  -webkit-border-radius: 10;\n"
"  -moz-border-radius: 10;\n"
"  border-radius: 10px;\n"
"  font: 10pt \"MV Boli\";\n"
"border:2px solid #333029;\n"
"    display:inline-block;\n"
"  font-size: 10px;\n"
"  padding: 5px 5px 5px 5px;\n"
"  text-decoration: none;\n"
"\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ccc2a6 5%, #eae0c2 100%);\n"
"    \n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
".QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.Btn_BROWSE.setCheckable(True)
        self.Btn_BROWSE.setChecked(True)
        self.Btn_BROWSE.setAutoDefault(False)
        self.Btn_BROWSE.setDefault(False)
        self.Btn_BROWSE.setFlat(False)
        self.Btn_BROWSE.setObjectName("Btn_BROWSE")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(180, 490, 41, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(150, 244, 31, 21))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/translation_page_seo_web_website_content_browser_language_translate_icon_230045.ico"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.c_quality = QtWidgets.QComboBox(Form)
        self.c_quality.setGeometry(QtCore.QRect(10, 190, 61, 22))
        self.c_quality.setStyleSheet("background-color: rgb(196, 203, 209);")
        self.c_quality.setObjectName("c_quality")
        self.c_quality.addItem("")
        self.c_quality.addItem("")
        self.c_quality.addItem("")
        self.c_quality.addItem("")
        self.c_quality.addItem("")
        self.c_quality.addItem("")
        self.check_subtitle = QtWidgets.QCheckBox(Form)
        self.check_subtitle.setGeometry(QtCore.QRect(10, 244, 141, 17))
        self.check_subtitle.setObjectName("check_subtitle")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(20, 460, 141, 16))
        self.label_12.setObjectName("label_12")
        self.lcdNumber_1 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_1.setGeometry(QtCore.QRect(180, 460, 41, 23))
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 31, 16))
        self.label_8.setStyleSheet("font: 10pt \"MV Boli\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.LINE_url = QtWidgets.QLineEdit(Form)
        self.LINE_url.setGeometry(QtCore.QRect(10, 90, 291, 20))
        self.LINE_url.setStyleSheet("border-style:sold;\n"
"border-radius:8px;\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.LINE_url.setText("")
        self.LINE_url.setObjectName("LINE_url")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 101, 20))
        self.label_9.setStyleSheet("font: 10pt \"MV Boli\";\n"
"")
        self.label_9.setObjectName("label_9")
        self.check_shut = QtWidgets.QCheckBox(Form)
        self.check_shut.setGeometry(QtCore.QRect(10, 334, 201, 17))
        self.check_shut.setObjectName("check_shut")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 51, 16))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("font: 10pt \"MV Boli\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(0, 70, 21, 21))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/newPrefix/url.ico"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(250, 16, 47, 31))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.check_audio = QtWidgets.QCheckBox(Form)
        self.check_audio.setGeometry(QtCore.QRect(10, 304, 141, 17))
        self.check_audio.setObjectName("check_audio")
        self.B_start = QtWidgets.QPushButton(Form)
        self.B_start.setGeometry(QtCore.QRect(140, 380, 111, 31))
        self.B_start.setMinimumSize(QtCore.QSize(111, 31))
        self.B_start.setMaximumSize(QtCore.QSize(111, 31))
        self.B_start.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.B_start.setStyleSheet(".QPushButton {\n"
"   background-color: rgb(222, 193, 161);\n"
"    box-shadow: 0px 1px 0px 0px #1c1b18;\n"
"    background:linear-gradient(to bottom, #eae0c2 5%, #ccc2a6 100%);\n"
"    font: 10pt \"MV Boli\";\n"
"    border-radius:15px;\n"
"    border:2px solid #333029;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    \n"
"    color: rgb(12, 12, 12);\n"
"    \n"
"    font-size:10px;\n"
"    font-weight:bold;\n"
"    padding:0px 0px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #ffffff;\n"
"}\n"
".QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ccc2a6 5%, #eae0c2 100%);\n"
"    \n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
".QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"\n"
"/*\n"
"\n"
"\n"
"*\\")
        self.B_start.setDefault(False)
        self.B_start.setFlat(False)
        self.B_start.setObjectName("B_start")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(140, 308, 21, 21))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/newPrefix/iconfinder-musicmelodysoundaudio04-4105577_113862.ico"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(10, 530, 371, 20))
        self.progressBar.setStyleSheet(".QProgressBar {\n"
"\n"
"    background-color: rgb(200, 200, 200);\n"
"    \n"
"    color: rgb(24, 24, 24);\n"
"    border-style:sold;\n"
"    border-radius:10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"        \n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(250, 244, 254, 255), stop:1 rgba(210, 242, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 59)
        self.progressBar.setObjectName("progressBar")
        self.L_language = QtWidgets.QComboBox(Form)
        self.L_language.setGeometry(QtCore.QRect(160, 274, 69, 22))
        self.L_language.setStyleSheet("background-color: rgb(196, 203, 209);")
        self.L_language.setObjectName("L_language")
        self.L_language.addItem("")
        self.L_language.addItem("")
        self.L_language.addItem("")
        self.L_language.addItem("")
        self.check_trans = QtWidgets.QCheckBox(Form)
        self.check_trans.setGeometry(QtCore.QRect(10, 274, 151, 17))
        self.check_trans.setObjectName("check_trans")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(280, 20, 47, 13))
        self.label_15.setText("")
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(100, 10, 61, 41))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/newPrefix/photo_٢٠٢٣-٠٦-٠٥_١٧-٣١-١٨-removebg-preview.ico"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "T.D.S Downloder"))
        self.label_10.setText(_translate("Form", "Current vedio number"))
        self.Btn_BROWSE.setToolTip(_translate("Form", "<html><head/><body><p>يوسف حسن</p><p><br/></p></body></html>"))
        self.Btn_BROWSE.setText(_translate("Form", "BROWSE"))
        self.c_quality.setItemText(0, _translate("Form", "1080"))
        self.c_quality.setItemText(1, _translate("Form", "720"))
        self.c_quality.setItemText(2, _translate("Form", "480"))
        self.c_quality.setItemText(3, _translate("Form", "360"))
        self.c_quality.setItemText(4, _translate("Form", "240"))
        self.c_quality.setItemText(5, _translate("Form", "144"))
        self.check_subtitle.setText(_translate("Form", "Download Subtitle"))
        self.label_12.setText(_translate("Form", "Number of Vedios"))
        self.label_8.setText(_translate("Form", "URL"))
        self.label_9.setText(_translate("Form", "Download Path "))
        self.check_shut.setText(_translate("Form", "ShutDown after Download"))
        self.label_7.setText(_translate("Form", "Quality"))
        self.check_audio.setText(_translate("Form", "Download as audio"))
        self.B_start.setText(_translate("Form", "Start Download"))
        self.L_language.setItemText(0, _translate("Form", "Arabic"))
        self.L_language.setItemText(1, _translate("Form", "English"))
        self.L_language.setItemText(2, _translate("Form", "Russian"))
        self.L_language.setItemText(3, _translate("Form", "German "))
        self.check_trans.setText(_translate("Form", "Translate Subtitle To "))
import icons_rc
