# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\BRMAGA\python\UI projects\restorant\Restorant1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1367, 804)
        Frame.setStyleSheet("QFrame{\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"\n"
".QGraphicsView{\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"}\n"
".QPushButton {\n"
"   background-color: rgb(222, 193, 161);\n"
"    box-shadow: 0px 1px 0px 0px #1c1b18;\n"
"    background:linear-gradient(to bottom, #eae0c2 5%, #ccc2a6 100%);\n"
"\n"
"    \n"
"    \n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    border-radius:13px;\n"
"    border:1px solid #333029;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    \n"
"    \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font-size:14px;\n"
"    \n"
"    padding:0px 0px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #ffffff;\n"
"}\n"
".QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ccc2a6 5%, #eae0c2 100%);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"        \n"
"    background-color: rgb(24, 24, 24);\n"
"\n"
"}\n"
".QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid rgb(102, 102, 102);\n"
"border-radius:10px;\n"
"font: 9pt \"Droid Sans Arabic\";\n"
"}\n"
".QComboBox{\n"
"font-size:15px;\n"
"  font: 11pt \"Droid Sans Arabic\";\n"
"    padding:0px 0px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #ffffff;\n"
"    text-align: center;\n"
"    border: 1px solid rgb(102, 102, 102);\n"
"\n"
"}\n"
".QLabel{\n"
"font-size:13px;\n"
"font: 63 9pt \"Segoe UI Semibold\";\n"
"    \n"
"    padding:0px 0px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #ffffff;\n"
"}\n"
".QTableWidget{\n"
"font-size:18px;\n"
"}")
        self.graphicsView = QtWidgets.QGraphicsView(Frame)
        self.graphicsView.setGeometry(QtCore.QRect(10, 670, 161, 121))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(560, 640, 81, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size:13px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(20, 690, 141, 41))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(20, 740, 141, 41))
        self.label_3.setMinimumSize(QtCore.QSize(141, 41))
        self.label_3.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);\n"
"text-align: center;")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(Frame)
        self.label_10.setGeometry(QtCore.QRect(30, 680, 41, 41))
        self.label_10.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/newPrefix/15.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_2.setGeometry(QtCore.QRect(180, 670, 161, 121))
        self.graphicsView_2.setAutoFillBackground(False)
        self.graphicsView_2.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(190, 690, 141, 41))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(Frame)
        self.label_11.setGeometry(QtCore.QRect(200, 680, 41, 41))
        self.label_11.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/newPrefix/customer_person_people_woman_you_1627.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(190, 740, 141, 41))
        self.label_5.setMinimumSize(QtCore.QSize(141, 41))
        self.label_5.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);\n"
"text-align: center;")
        self.label_5.setObjectName("label_5")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_3.setGeometry(QtCore.QRect(350, 670, 161, 121))
        self.graphicsView_3.setAutoFillBackground(False)
        self.graphicsView_3.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setGeometry(QtCore.QRect(360, 690, 141, 41))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.graphicsView_4 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_4.setGeometry(QtCore.QRect(530, 670, 161, 121))
        self.graphicsView_4.setAutoFillBackground(False)
        self.graphicsView_4.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(540, 690, 141, 41))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.graphicsView_5 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_5.setGeometry(QtCore.QRect(710, 670, 161, 121))
        self.graphicsView_5.setAutoFillBackground(False)
        self.graphicsView_5.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.label_8 = QtWidgets.QLabel(Frame)
        self.label_8.setGeometry(QtCore.QRect(720, 690, 141, 41))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.graphicsView_6 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_6.setGeometry(QtCore.QRect(880, 670, 161, 121))
        self.graphicsView_6.setAutoFillBackground(False)
        self.graphicsView_6.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.label_9 = QtWidgets.QLabel(Frame)
        self.label_9.setGeometry(QtCore.QRect(890, 690, 141, 41))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.graphicsView_7 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_7.setGeometry(QtCore.QRect(1050, 670, 161, 121))
        self.graphicsView_7.setAutoFillBackground(False)
        self.graphicsView_7.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.label_12 = QtWidgets.QLabel(Frame)
        self.label_12.setGeometry(QtCore.QRect(1060, 690, 141, 41))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:13px;\n"
"    border:1px solid #333029;")
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Frame)
        self.label_13.setGeometry(QtCore.QRect(370, 680, 41, 41))
        self.label_13.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/newPrefix/15.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Frame)
        self.label_14.setGeometry(QtCore.QRect(360, 740, 141, 41))
        self.label_14.setMinimumSize(QtCore.QSize(141, 41))
        self.label_14.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);\n"
"text-align: center;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Frame)
        self.label_15.setGeometry(QtCore.QRect(550, 680, 41, 41))
        self.label_15.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/newPrefix/customer_person_people_woman_you_1627.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Frame)
        self.label_16.setGeometry(QtCore.QRect(540, 740, 141, 41))
        self.label_16.setMinimumSize(QtCore.QSize(141, 41))
        self.label_16.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);\n"
"text-align: center;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Frame)
        self.label_17.setGeometry(QtCore.QRect(730, 680, 41, 41))
        self.label_17.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/newPrefix/15.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Frame)
        self.label_18.setGeometry(QtCore.QRect(720, 740, 141, 41))
        self.label_18.setMinimumSize(QtCore.QSize(141, 41))
        self.label_18.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);\n"
"text-align: center;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Frame)
        self.label_19.setGeometry(QtCore.QRect(900, 680, 41, 41))
        self.label_19.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/newPrefix/15.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Frame)
        self.label_20.setGeometry(QtCore.QRect(890, 740, 141, 41))
        self.label_20.setMinimumSize(QtCore.QSize(141, 41))
        self.label_20.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);\n"
"text-align: center;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Frame)
        self.label_21.setGeometry(QtCore.QRect(1070, 680, 41, 41))
        self.label_21.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/newPrefix/15.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Frame)
        self.label_22.setGeometry(QtCore.QRect(1060, 740, 141, 41))
        self.label_22.setMinimumSize(QtCore.QSize(141, 41))
        self.label_22.setStyleSheet("border-radius:13px;\n"
"    border:1px solid #333029;color: rgb(255, 255, 255);\n"
"text-align: center;")
        self.label_22.setObjectName("label_22")
        self.graphicsView_8 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_8.setGeometry(QtCore.QRect(10, 391, 1201, 251))
        self.graphicsView_8.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.label_23 = QtWidgets.QLabel(Frame)
        self.label_23.setGeometry(QtCore.QRect(560, 400, 81, 20))
        self.label_23.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font-size:15px;")
        self.label_23.setObjectName("label_23")
        self.graphicsView_9 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_9.setGeometry(QtCore.QRect(20, 430, 1181, 201))
        self.graphicsView_9.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"background-color: rgb(107, 107, 107);")
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.graphicsView_10 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_10.setGeometry(QtCore.QRect(10, 10, 221, 71))
        self.graphicsView_10.setAutoFillBackground(False)
        self.graphicsView_10.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.graphicsView_11 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_11.setGeometry(QtCore.QRect(70, 20, 141, 51))
        self.graphicsView_11.setAutoFillBackground(False)
        self.graphicsView_11.setStyleSheet("\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_11.setObjectName("graphicsView_11")
        self.label_24 = QtWidgets.QLabel(Frame)
        self.label_24.setGeometry(QtCore.QRect(90, 30, 101, 21))
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setStyleSheet("font-size:14px;color: rgb(255, 255, 255);")
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Frame)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.label_25.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/newPrefix/history.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.graphicsView_12 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_12.setGeometry(QtCore.QRect(250, 10, 231, 71))
        self.graphicsView_12.setAutoFillBackground(False)
        self.graphicsView_12.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.label_29 = QtWidgets.QLabel(Frame)
        self.label_29.setGeometry(QtCore.QRect(350, 50, 41, 21))
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_29.setObjectName("label_29")
        self.graphicsView_13 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_13.setGeometry(QtCore.QRect(310, 20, 141, 51))
        self.graphicsView_13.setAutoFillBackground(False)
        self.graphicsView_13.setStyleSheet("\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_13.setObjectName("graphicsView_13")
        self.label_26 = QtWidgets.QLabel(Frame)
        self.label_26.setGeometry(QtCore.QRect(260, 20, 41, 51))
        self.label_26.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);")
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(":/newPrefix/team.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Frame)
        self.label_27.setGeometry(QtCore.QRect(330, 30, 101, 21))
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setStyleSheet("font-size:14px;color: rgb(255, 255, 255);")
        self.label_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_27.setObjectName("label_27")
        self.graphicsView_14 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_14.setGeometry(QtCore.QRect(500, 10, 231, 71))
        self.graphicsView_14.setAutoFillBackground(False)
        self.graphicsView_14.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_14.setObjectName("graphicsView_14")
        self.label_31 = QtWidgets.QLabel(Frame)
        self.label_31.setGeometry(QtCore.QRect(570, 50, 41, 21))
        self.label_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_31.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_31.setTextFormat(QtCore.Qt.AutoText)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(Frame)
        self.label_32.setGeometry(QtCore.QRect(510, 20, 41, 41))
        self.label_32.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);")
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap(":/newPrefix/businesspackagewarningbox_negocio_paquete_advertencia_2337.ico"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.graphicsView_15 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_15.setGeometry(QtCore.QRect(560, 20, 141, 51))
        self.graphicsView_15.setAutoFillBackground(False)
        self.graphicsView_15.setStyleSheet("\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_15.setObjectName("graphicsView_15")
        self.label_33 = QtWidgets.QLabel(Frame)
        self.label_33.setGeometry(QtCore.QRect(590, 30, 81, 21))
        self.label_33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_33.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size:14px;")
        self.label_33.setTextFormat(QtCore.Qt.AutoText)
        self.label_33.setObjectName("label_33")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(Frame)
        self.lcdNumber_3.setGeometry(QtCore.QRect(610, 120, 51, 21))
        self.lcdNumber_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_3.setSmallDecimalPoint(True)
        self.lcdNumber_3.setProperty("value", 500.0)
        self.lcdNumber_3.setProperty("intValue", 500)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.label_34 = QtWidgets.QLabel(Frame)
        self.label_34.setGeometry(QtCore.QRect(570, 120, 51, 21))
        self.label_34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_34.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_34.setTextFormat(QtCore.Qt.AutoText)
        self.label_34.setObjectName("label_34")
        self.graphicsView_16 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_16.setGeometry(QtCore.QRect(750, 10, 231, 71))
        self.graphicsView_16.setAutoFillBackground(False)
        self.graphicsView_16.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_16.setObjectName("graphicsView_16")
        self.label_36 = QtWidgets.QLabel(Frame)
        self.label_36.setGeometry(QtCore.QRect(760, 30, 41, 41))
        self.label_36.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);")
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap(":/newPrefix/boxes.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.graphicsView_17 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_17.setGeometry(QtCore.QRect(810, 20, 141, 51))
        self.graphicsView_17.setAutoFillBackground(False)
        self.graphicsView_17.setStyleSheet("\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_17.setObjectName("graphicsView_17")
        self.label_37 = QtWidgets.QLabel(Frame)
        self.label_37.setGeometry(QtCore.QRect(830, 30, 91, 21))
        self.label_37.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_37.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size:14px;")
        self.label_37.setTextFormat(QtCore.Qt.AutoText)
        self.label_37.setObjectName("label_37")
        self.graphicsView_18 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_18.setGeometry(QtCore.QRect(1000, 10, 211, 71))
        self.graphicsView_18.setAutoFillBackground(False)
        self.graphicsView_18.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_18.setObjectName("graphicsView_18")
        self.label_39 = QtWidgets.QLabel(Frame)
        self.label_39.setGeometry(QtCore.QRect(1020, 50, 41, 21))
        self.label_39.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_39.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_39.setTextFormat(QtCore.Qt.AutoText)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(Frame)
        self.label_40.setGeometry(QtCore.QRect(1010, 20, 51, 51))
        self.label_40.setStyleSheet("\n"
"background-color: rgb(72, 72, 72);")
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap(":/newPrefix/profit.png"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.graphicsView_19 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_19.setGeometry(QtCore.QRect(1060, 20, 141, 51))
        self.graphicsView_19.setAutoFillBackground(False)
        self.graphicsView_19.setStyleSheet("\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_19.setObjectName("graphicsView_19")
        self.label_41 = QtWidgets.QLabel(Frame)
        self.label_41.setGeometry(QtCore.QRect(1090, 30, 81, 21))
        self.label_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_41.setStyleSheet("color: rgb(255, 255, 255);font-size:14px;")
        self.label_41.setTextFormat(QtCore.Qt.AutoText)
        self.label_41.setObjectName("label_41")
        self.graphicsView_20 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_20.setGeometry(QtCore.QRect(10, 90, 471, 291))
        self.graphicsView_20.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.graphicsView_20.setObjectName("graphicsView_20")
        self.label_43 = QtWidgets.QLabel(Frame)
        self.label_43.setGeometry(QtCore.QRect(170, 100, 141, 20))
        self.label_43.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font-size:15px;")
        self.label_43.setObjectName("label_43")
        self.graphicsView_22 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_22.setGeometry(QtCore.QRect(20, 130, 451, 241))
        self.graphicsView_22.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"background-color: rgb(107, 107, 107);")
        self.graphicsView_22.setObjectName("graphicsView_22")
        self.graphicsView_21 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_21.setGeometry(QtCore.QRect(500, 90, 711, 291))
        self.graphicsView_21.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"")
        self.graphicsView_21.setObjectName("graphicsView_21")
        self.graphicsView_23 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_23.setGeometry(QtCore.QRect(510, 130, 691, 241))
        self.graphicsView_23.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"background-color: rgb(107, 107, 107);")
        self.graphicsView_23.setObjectName("graphicsView_23")
        self.label_44 = QtWidgets.QLabel(Frame)
        self.label_44.setGeometry(QtCore.QRect(740, 100, 141, 20))
        self.label_44.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font-size:15px;")
        self.label_44.setObjectName("label_44")
        self.graphicsView_24 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_24.setGeometry(QtCore.QRect(90, 140, 371, 61))
        self.graphicsView_24.setAutoFillBackground(False)
        self.graphicsView_24.setStyleSheet("\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_24.setObjectName("graphicsView_24")
        self.graphicsView_25 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_25.setGeometry(QtCore.QRect(90, 220, 371, 61))
        self.graphicsView_25.setAutoFillBackground(False)
        self.graphicsView_25.setStyleSheet("\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_25.setObjectName("graphicsView_25")
        self.graphicsView_26 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_26.setGeometry(QtCore.QRect(90, 300, 371, 61))
        self.graphicsView_26.setAutoFillBackground(False)
        self.graphicsView_26.setStyleSheet("\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_26.setObjectName("graphicsView_26")
        self.label_45 = QtWidgets.QLabel(Frame)
        self.label_45.setGeometry(QtCore.QRect(30, 140, 51, 51))
        self.label_45.setStyleSheet("background-color: rgb(107, 107, 107);")
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap(":/newPrefix/11.png"))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(Frame)
        self.label_46.setGeometry(QtCore.QRect(30, 220, 51, 51))
        self.label_46.setStyleSheet("background-color: rgb(107, 107, 107);")
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap(":/newPrefix/2.png"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(Frame)
        self.label_47.setGeometry(QtCore.QRect(30, 300, 51, 51))
        self.label_47.setStyleSheet("background-color: rgb(107, 107, 107);")
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap(":/newPrefix/33.png"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.graphicsView_27 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_27.setGeometry(QtCore.QRect(1220, 90, 141, 701))
        self.graphicsView_27.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"background-color: rgb(107, 107, 107);")
        self.graphicsView_27.setObjectName("graphicsView_27")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(1230, 120, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.graphicsView_28 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_28.setGeometry(QtCore.QRect(1220, 10, 141, 71))
        self.graphicsView_28.setAutoFillBackground(False)
        self.graphicsView_28.setStyleSheet("\n"
"background-color: rgb(107, 107, 107);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.graphicsView_28.setObjectName("graphicsView_28")
        self.label_48 = QtWidgets.QLabel(Frame)
        self.label_48.setGeometry(QtCore.QRect(1300, 20, 51, 21))
        self.label_48.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_48.setStyleSheet("background-color: rgb(107, 107, 107);\n"
"font-size:14px;\n"
"color: rgb(255, 255, 255);")
        self.label_48.setTextFormat(QtCore.Qt.AutoText)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Frame)
        self.label_49.setGeometry(QtCore.QRect(1270, 50, 81, 21))
        self.label_49.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_49.setStyleSheet("background-color: rgb(107, 107, 107);\n"
"font-size:14px;\n"
"color: rgb(255, 255, 255);")
        self.label_49.setTextFormat(QtCore.Qt.AutoText)
        self.label_49.setObjectName("label_49")
        self.label_35 = QtWidgets.QLabel(Frame)
        self.label_35.setGeometry(QtCore.QRect(1230, 20, 41, 41))
        self.label_35.setStyleSheet("background-color: rgb(107, 107, 107);")
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap(":/newPrefix/15.png"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.pushButton_2 = QtWidgets.QPushButton(Frame)
        self.pushButton_2.setGeometry(QtCore.QRect(1230, 180, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Frame)
        self.pushButton_3.setGeometry(QtCore.QRect(1230, 240, 121, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Frame)
        self.pushButton_4.setGeometry(QtCore.QRect(1230, 420, 121, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Frame)
        self.pushButton_5.setGeometry(QtCore.QRect(1230, 300, 121, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Frame)
        self.pushButton_6.setGeometry(QtCore.QRect(1230, 360, 121, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(Frame)
        self.pushButton_8.setGeometry(QtCore.QRect(1230, 480, 121, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit = QtWidgets.QLineEdit(Frame)
        self.lineEdit.setGeometry(QtCore.QRect(600, 50, 71, 20))
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(830, 50, 91, 20))
        self.lineEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(1080, 50, 91, 20))
        self.lineEdit_3.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(350, 50, 71, 20))
        self.lineEdit_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 50, 71, 20))
        self.lineEdit_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(190, 150, 141, 21))
        self.lineEdit_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"color:rgb(255, 186, 87);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(190, 170, 141, 21))
        self.lineEdit_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 186, 87);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 230, 141, 21))
        self.lineEdit_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(158, 158, 158);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(190, 250, 141, 21))
        self.lineEdit_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(158, 158, 158);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_10.setGeometry(QtCore.QRect(190, 330, 141, 21))
        self.lineEdit_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(252, 150, 55);\n"
"")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_11.setGeometry(QtCore.QRect(190, 310, 141, 21))
        self.lineEdit_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius:15px;\n"
"    border:1px solid #333029;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(252, 150, 55);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_28 = QtWidgets.QLabel(Frame)
        self.label_28.setGeometry(QtCore.QRect(40, 440, 371, 181))
        self.label_28.setStyleSheet("background-color: rgb(107, 107, 107);")
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/newPrefix/Profit-Graph.gif"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(Frame)
        self.label_30.setGeometry(QtCore.QRect(500, 440, 691, 181))
        self.label_30.setStyleSheet("background-color: rgb(107, 107, 107);")
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap(":/newPrefix/PlotTypes_Bar_MultipleBars.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "موظفين الفرع"))
        self.label_2.setText(_translate("Frame", "     يوسف حسن "))
        self.label_3.setText(_translate("Frame", "              مدير الفرع "))
        self.label_4.setText(_translate("Frame", "     ايمان احمد"))
        self.label_5.setText(_translate("Frame", "              مدير الفرع "))
        self.label_6.setText(_translate("Frame", "     عبد الرحمان "))
        self.label_7.setText(_translate("Frame", "     اسماء علي  "))
        self.label_8.setText(_translate("Frame", "     محمد خالد"))
        self.label_9.setText(_translate("Frame", "     محمد حسن "))
        self.label_12.setText(_translate("Frame", "     يوسف علام "))
        self.label_14.setText(_translate("Frame", "           مندوب مبيعات  "))
        self.label_16.setText(_translate("Frame", "                   كاشير "))
        self.label_18.setText(_translate("Frame", "                 محاسب  "))
        self.label_20.setText(_translate("Frame", "              عامل نظافه"))
        self.label_22.setText(_translate("Frame", "            مندوب مبيعات "))
        self.label_23.setText(_translate("Frame", "أحصائيات"))
        self.label_24.setText(_translate("Frame", "  معاملات اليوم"))
        self.label_29.setText(_translate("Frame", " معامله"))
        self.label_27.setText(_translate("Frame", "عدد المستخدمين"))
        self.label_31.setText(_translate("Frame", " معامله"))
        self.label_33.setText(_translate("Frame", "منتجات نفذت"))
        self.label_34.setText(_translate("Frame", "منتج"))
        self.label_37.setText(_translate("Frame", "جميع المنتجات"))
        self.label_39.setText(_translate("Frame", " معامله"))
        self.label_41.setText(_translate("Frame", "صافي الربح"))
        self.label_43.setText(_translate("Frame", "المنتجات الأكثر مبيعا"))
        self.label_44.setText(_translate("Frame", "نظره عامه"))
        self.pushButton.setText(_translate("Frame", "لوحه التحكم"))
        self.label_48.setText(_translate("Frame", "  مرحبا !"))
        self.label_49.setText(_translate("Frame", "يوسف حسن "))
        self.pushButton_2.setText(_translate("Frame", "الموظفين"))
        self.pushButton_3.setText(_translate("Frame", "العملاء"))
        self.pushButton_4.setText(_translate("Frame", "الفئات"))
        self.pushButton_5.setText(_translate("Frame", "الموردين"))
        self.pushButton_6.setText(_translate("Frame", "الأصناف"))
        self.pushButton_8.setText(_translate("Frame", "تواصل معانا "))
        self.lineEdit.setText(_translate("Frame", "500 منتج"))
        self.lineEdit_2.setText(_translate("Frame", "12354 منتج"))
        self.lineEdit_3.setText(_translate("Frame", "10920 جم"))
        self.lineEdit_4.setText(_translate("Frame", "16 مسنخدم"))
        self.lineEdit_5.setText(_translate("Frame", "24 معامله"))
        self.lineEdit_6.setText(_translate("Frame", "وجبه شاورما فراخ"))
        self.lineEdit_7.setText(_translate("Frame", "150 معامله بيع هذا الشهر"))
        self.lineEdit_8.setText(_translate("Frame", "كريب فاهيتا لحمه"))
        self.lineEdit_9.setText(_translate("Frame", "  140 معامله بيع هذا الشهر"))
        self.lineEdit_10.setText(_translate("Frame", "    130 معامله بيع هذا الشهر"))
        self.lineEdit_11.setText(_translate("Frame", "مكرونه وايت صوص"))
import icons_rc
