# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\BRMAGA\python\UI projects\pharmasy\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(799, 509)
        Frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 511))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(45, 173, 228, 248), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qconicalgradient(cx:1, cy:1, angle:0, stop:0 rgba(70, 173, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(560, 80, 71, 41))
        self.label_2.setStyleSheet("font: 18pt \"Segoe UI Semilight\";\n"
"font: 63 18pt \"Segoe UI Semibold\";\n"
"font: 57 18pt \"Yu Gothic Medium\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Frame)
        self.lineEdit.setGeometry(QtCore.QRect(440, 150, 311, 41))
        self.lineEdit.setStyleSheet("font: 57 10pt \"Yu Gothic Medium\";\n"
"color: rgb(150, 150, 150);\n"
"        border-radius:6px;\n"
"    border:1px solid#acacac ;\n"
"")
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(440, 220, 311, 41))
        self.lineEdit_2.setStyleSheet("font: 57 10pt \"Yu Gothic Medium\";\n"
"color: rgb(150, 150, 150);\n"
"        border-radius:6px;\n"
"    border:1px solid #acacac;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(440, 300, 311, 41))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/1.png);\n"
"border-radius:10px;\n"
"")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/2.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(440, 300, 311, 41))
        self.pushButton.setStyleSheet("\n"
"\n"
".QPushButton {\n"
"background-image: url(:/newPrefix/2.png);\n"
"   background-color: rgb(222, 193, 161);\n"
"    box-shadow: 0px 1px 0px 0px #1c1b18;\n"
"    background:linear-gradient(to bottom, #eae0c2 5%, #ccc2a6 100%);\n"
"\n"
"    \n"
"    font: 14pt \"Segoe UI Historic\";\n"
"    border-radius:6px;\n"
"    border:1px solid #333029;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font-size:16px;\n"
"\n"
"    \n"
"    padding:0px 0px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #ffffff;\n"
"border-width: 0px;\n"
"}\n"
".QPushButton:hover {\n"
"    \n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(530, 360, 161, 31))
        self.label_4.setStyleSheet("font: 57 11pt \"Yu Gothic Medium\";\n"
"color: rgb(150, 150, 150);\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(510, 410, 151, 31))
        self.label_5.setStyleSheet("font: 57 11pt \"Yu Gothic Medium\";\n"
"color: rgb(150, 150, 150);\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(Frame)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 410, 131, 31))
        self.pushButton_2.setStyleSheet("\n"
"\n"
".QPushButton {\n"
"background-image: url(:/newPrefix/2.png);\n"
"   background-color: rgb(222, 193, 161);\n"
"    box-shadow: 0px 1px 0px 0px #1c1b18;\n"
"    background:linear-gradient(to bottom, #eae0c2 5%, #ccc2a6 100%);\n"
"\n"
"    \n"
"    font: 57 11pt \"Yu Gothic Medium\";\n"
"\n"
"    border-radius:6px;\n"
"    border:1px solid #333029;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    font-size:15px;\n"
"\n"
"    \n"
"    padding:0px 0px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #ffffff;\n"
"border-width: 0px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_2.setText(_translate("Frame", "Login"))
        self.lineEdit.setText(_translate("Frame", "  Email"))
        self.lineEdit_2.setText(_translate("Frame", "  Password"))
        self.pushButton.setText(_translate("Frame", "Login"))
        self.label_4.setText(_translate("Frame", "   Forget password ?"))
        self.label_5.setText(_translate("Frame", "Don\'t have account ?"))
        self.pushButton_2.setText(_translate("Frame", "Register"))
import icons_rc
