# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\BRMAGA\python\UI projects\pharmasy\pharmasy main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1357, 692)
        Frame.setStyleSheet(".QPushButton{\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"border:1px solid #1b5a90;\n"
"\n"
"}\n"
".QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ccc2a6 5%, #eae0c2 100%);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"        \n"
"    \n"
"    background-color: rgb(0, 208, 241);\n"
"\n"
"}\n"
".QFrame{\n"
"background-color: rgb(248, 249, 250);\n"
"}")
        self.graphicsView = QtWidgets.QGraphicsView(Frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1361, 51))
        self.graphicsView.setStyleSheet("border:1px solid #ffffff;")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_2.setGeometry(QtCore.QRect(-10, 50, 256, 661))
        self.graphicsView_2.setStyleSheet("border:1px solid #ffffff;\n"
"background-color: rgb(27, 90, 144);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 80, 201, 41))
        self.pushButton.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(40, 60, 47, 13))
        self.label.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 130, 201, 41))
        self.pushButton_2.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 180, 201, 41))
        self.pushButton_3.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 230, 201, 41))
        self.pushButton_4.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 380, 201, 41))
        self.pushButton_5.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Frame)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 430, 201, 41))
        self.pushButton_6.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Frame)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 280, 201, 41))
        self.pushButton_7.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Frame)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 330, 201, 41))
        self.pushButton_8.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Frame)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 530, 201, 41))
        self.pushButton_9.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Frame)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 480, 201, 41))
        self.pushButton_10.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Frame)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 580, 201, 41))
        self.pushButton_11.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(30, 91, 31, 20))
        self.label_2.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/dashboard-xxl.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(30, 240, 31, 20))
        self.label_3.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/add-to-cart.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 31, 20))
        self.label_4.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/product.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 31, 20))
        self.label_5.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/categories.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setGeometry(QtCore.QRect(30, 389, 31, 20))
        self.label_6.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/newPrefix/seo-report.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(30, 439, 31, 31))
        self.label_7.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/newPrefix/password-code.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Frame)
        self.label_8.setGeometry(QtCore.QRect(30, 339, 31, 20))
        self.label_8.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/newPrefix/teamwork.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Frame)
        self.label_9.setGeometry(QtCore.QRect(30, 290, 31, 20))
        self.label_9.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/newPrefix/sales.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Frame)
        self.label_10.setGeometry(QtCore.QRect(30, 590, 31, 21))
        self.label_10.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/newPrefix/settings-5-xxl.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Frame)
        self.label_11.setGeometry(QtCore.QRect(30, 490, 31, 20))
        self.label_11.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/newPrefix/conference-xxl.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Frame)
        self.label_12.setGeometry(QtCore.QRect(30, 540, 31, 20))
        self.label_12.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/newPrefix/guest-xxl.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Frame)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 241, 51))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/newPrefix/222.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.lineEdit = QtWidgets.QLineEdit(Frame)
        self.lineEdit.setGeometry(QtCore.QRect(270, 50, 321, 31))
        self.lineEdit.setStyleSheet("border:1px solid#f8f9fa ;\n"
"font: 18pt \"Segoe UI Emoji\";\n"
"background-color: rgb(248, 249, 250);\n"
"")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_3.setGeometry(QtCore.QRect(280, 100, 251, 131))
        self.graphicsView_3.setStyleSheet("border:1px solid #c2c2c2 ;")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_4.setGeometry(QtCore.QRect(550, 100, 251, 131))
        self.graphicsView_4.setStyleSheet("border:1px solid #c2c2c2 ;")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_5.setGeometry(QtCore.QRect(1090, 100, 251, 131))
        self.graphicsView_5.setStyleSheet("border:1px solid #c2c2c2 ;")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_6.setGeometry(QtCore.QRect(820, 100, 251, 131))
        self.graphicsView_6.setStyleSheet("border:1px solid #c2c2c2 ;")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 240, 521, 51))
        self.lineEdit_2.setStyleSheet("border:1px solid #c2c2c2 ;\n"
"font: 18pt \"Segoe UI Emoji\";\n"
"\n"
"")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 290, 521, 51))
        self.lineEdit_3.setStyleSheet("border:1px solid #c2c2c2 ;font: 18pt \"Segoe UI Emoji\";\n"
"background-color: rgb(248, 249, 250);\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_14 = QtWidgets.QLabel(Frame)
        self.label_14.setGeometry(QtCore.QRect(310, 290, 91, 41))
        self.label_14.setStyleSheet("font: 12pt \"Segoe UI Emoji\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Frame)
        self.label_15.setGeometry(QtCore.QRect(440, 290, 91, 41))
        self.label_15.setStyleSheet("font: 12pt \"Segoe UI Emoji\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Frame)
        self.label_16.setGeometry(QtCore.QRect(560, 290, 91, 41))
        self.label_16.setStyleSheet("font: 12pt \"Segoe UI Emoji\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Frame)
        self.label_17.setGeometry(QtCore.QRect(680, 290, 91, 41))
        self.label_17.setStyleSheet("font: 12pt \"Segoe UI Emoji\";")
        self.label_17.setObjectName("label_17")
        self.lineEdit_4 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(820, 240, 521, 51))
        self.lineEdit_4.setStyleSheet("border:1px solid #c2c2c2 ;\n"
"font: 18pt \"Segoe UI Emoji\";\n"
"\n"
"")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.progressBar = QtWidgets.QProgressBar(Frame)
        self.progressBar.setGeometry(QtCore.QRect(290, 210, 231, 16))
        self.progressBar.setStyleSheet(".QProgressBar {\n"
"border-radius:6px;\n"
"border:1px solid #00d0f1 ;\n"
"color: rgb(0, 208, 241);\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"        \n"
"    \n"
"    background-color: rgb(0, 208, 241);\n"
"}\n"
"")
        self.progressBar.setProperty("value", 50)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_18 = QtWidgets.QLabel(Frame)
        self.label_18.setGeometry(QtCore.QRect(300, 190, 161, 16))
        self.label_18.setStyleSheet("font: 57 10pt \"Yu Gothic Medium\";\n"
"color: rgb(150, 150, 150);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Frame)
        self.label_19.setGeometry(QtCore.QRect(570, 190, 161, 16))
        self.label_19.setStyleSheet("font: 57 10pt \"Yu Gothic Medium\";\n"
"color: rgb(150, 150, 150);")
        self.label_19.setObjectName("label_19")
        self.progressBar_2 = QtWidgets.QProgressBar(Frame)
        self.progressBar_2.setGeometry(QtCore.QRect(560, 210, 231, 16))
        self.progressBar_2.setStyleSheet(".QProgressBar {\n"
"    color: rgb(80, 179, 111);\n"
"border-radius:6px;\n"
"border:1px solid #50b36f ;\n"
"\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"        \n"
"    \n"
"    background-color:  rgb(80, 179, 111);\n"
"    \n"
"\n"
"}\n"
"")
        self.progressBar_2.setProperty("value", 50)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_20 = QtWidgets.QLabel(Frame)
        self.label_20.setGeometry(QtCore.QRect(840, 190, 161, 16))
        self.label_20.setStyleSheet("font: 57 10pt \"Yu Gothic Medium\";\n"
"color: rgb(150, 150, 150);")
        self.label_20.setObjectName("label_20")
        self.progressBar_3 = QtWidgets.QProgressBar(Frame)
        self.progressBar_3.setGeometry(QtCore.QRect(830, 210, 231, 16))
        self.progressBar_3.setStyleSheet(".QProgressBar {\n"
"border-radius:6px;\n"
"border:1px solid #e84646 ;\n"
"\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"        \n"
"    \n"
"    background-color: rgb(232, 70, 70);\n"
"}\n"
"")
        self.progressBar_3.setProperty("value", 20)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(Frame)
        self.progressBar_4.setGeometry(QtCore.QRect(1100, 210, 231, 16))
        self.progressBar_4.setStyleSheet(".QProgressBar {\n"
"border-radius:6px;\n"
"border:1px solid #ffc809 ;\n"
"color: rgb(0, 208, 241);\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"        \n"
"    \n"
"    background-color: rgb(255, 200, 9);\n"
"}\n"
"")
        self.progressBar_4.setProperty("value", 25)
        self.progressBar_4.setTextVisible(False)
        self.progressBar_4.setObjectName("progressBar_4")
        self.label_21 = QtWidgets.QLabel(Frame)
        self.label_21.setGeometry(QtCore.QRect(1110, 190, 161, 16))
        self.label_21.setStyleSheet("font: 57 10pt \"Yu Gothic Medium\";\n"
"color: rgb(150, 150, 150);")
        self.label_21.setObjectName("label_21")
        self.lineEdit_5 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(420, 120, 101, 31))
        self.lineEdit_5.setStyleSheet("border:1px solid#ffffff ;\n"
"\n"
"font: 18pt \"Segoe UI Emoji\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(730, 120, 41, 31))
        self.lineEdit_6.setStyleSheet("border:1px solid#ffffff ;\n"
"\n"
"font: 18pt \"Segoe UI Emoji\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(1010, 120, 31, 31))
        self.lineEdit_7.setStyleSheet("border:1px solid#ffffff ;\n"
"\n"
"font: 18pt \"Segoe UI Emoji\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(1280, 120, 31, 31))
        self.lineEdit_8.setStyleSheet("border:1px solid#ffffff ;\n"
"\n"
"font: 18pt \"Segoe UI Emoji\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_22 = QtWidgets.QLabel(Frame)
        self.label_22.setGeometry(QtCore.QRect(310, 120, 61, 51))
        self.label_22.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/newPrefix/ss.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Frame)
        self.label_23.setGeometry(QtCore.QRect(580, 120, 51, 41))
        self.label_23.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/newPrefix/ddd.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Frame)
        self.label_24.setGeometry(QtCore.QRect(840, 120, 61, 51))
        self.label_24.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/newPrefix/delivery-box.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Frame)
        self.label_25.setGeometry(QtCore.QRect(1110, 120, 61, 51))
        self.label_25.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/newPrefix/cross.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.graphicsView_7 = QtWidgets.QGraphicsView(Frame)
        self.graphicsView_7.setGeometry(QtCore.QRect(820, 290, 521, 391))
        self.graphicsView_7.setStyleSheet("border:1px solid #c2c2c2 ;")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.label_26 = QtWidgets.QLabel(Frame)
        self.label_26.setGeometry(QtCore.QRect(840, 310, 491, 351))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(":/newPrefix/Figure_1.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Frame)
        self.label_27.setGeometry(QtCore.QRect(1310, 10, 31, 21))
        self.label_27.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap(":/newPrefix/logout.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Frame)
        self.label_28.setGeometry(QtCore.QRect(1220, 10, 31, 21))
        self.label_28.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/newPrefix/notification.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton.setText(_translate("Frame", "  Dashboard"))
        self.label.setText(_translate("Frame", "Main"))
        self.pushButton_2.setText(_translate("Frame", "  Categories"))
        self.pushButton_3.setText(_translate("Frame", "products"))
        self.pushButton_4.setText(_translate("Frame", "purchase"))
        self.pushButton_5.setText(_translate("Frame", "Reports  "))
        self.pushButton_6.setText(_translate("Frame", "          Access Control"))
        self.pushButton_7.setText(_translate("Frame", " Sales         "))
        self.pushButton_8.setText(_translate("Frame", "Supplier  "))
        self.pushButton_9.setText(_translate("Frame", "Profile   "))
        self.pushButton_10.setText(_translate("Frame", "Users      "))
        self.pushButton_11.setText(_translate("Frame", "Settings"))
        self.lineEdit.setText(_translate("Frame", "Welcome Youssif Allam"))
        self.lineEdit_2.setText(_translate("Frame", "    Today Sales"))
        self.label_14.setText(_translate("Frame", "Medicine"))
        self.label_15.setText(_translate("Frame", "Quantity"))
        self.label_16.setText(_translate("Frame", "Total price"))
        self.label_17.setText(_translate("Frame", "Date"))
        self.lineEdit_4.setText(_translate("Frame", "    Resources Sum"))
        self.label_18.setText(_translate("Frame", "Total Sales Cash"))
        self.label_19.setText(_translate("Frame", "Product Categories"))
        self.label_20.setText(_translate("Frame", "Expired Products"))
        self.label_21.setText(_translate("Frame", "Implemented Products"))
        self.lineEdit_5.setText(_translate("Frame", "EP 1500"))
        self.lineEdit_6.setText(_translate("Frame", "15"))
        self.lineEdit_7.setText(_translate("Frame", "3"))
        self.lineEdit_8.setText(_translate("Frame", "14"))
import icons_rc
